-- 1. Criar a tabela
create table if not exists public.captures (
  id bigint generated by default as identity primary key,
  device_id text not null,
  date date not null,
  time time not null,
  image_base64 text not null,
  created_at timestamptz not null default now()
);

-- 2. Criar índices para performance
create index if not exists captures_date_time_idx on public.captures (date, time);
create index if not exists captures_device_idx on public.captures (device_id);
create index if not exists captures_created_at_idx on public.captures (created_at);

-- 3. Habilitar RLS (Row Level Security)
alter table public.captures enable row level security;

-- 4. Política simples: permitir insert/select/delete para usuário anônimo (chave anon)
create policy "allow_anon_all_captures"
  on public.captures
  for all
  to anon
  using (true)
  with check (true);